uds:
  domain: uds.dev
  sso:
    enabled: false
    secretName: hello-world-sso
    selector: hello-world
  # Support for custom `network.allow` entries on the Package CR
  additionalNetworkAllow: []
  #    # Notice no `remoteGenerated` field here on custom internal rule
  #   - direction: Ingress
  #     selector:
  #       app: jenkins
  #     remoteNamespace: jenkins
  #     remoteSelector:
  #       app: jenkins
  #     port: 8180
  #     description: "Ingress from Jenkins"
  #   # No `remoteNamespace`, `remoteSelector`, or `port` fields on rule to `remoteGenerated`
  #   - direction: Egress
  #     selector:
  #       app: webservice
  #     remoteGenerated: Anywhere
  #     description: "Egress from hello-world"
