# This secret will be used if sso is disabled, instead of the templated one in uds-package.yaml.
# Hello World needs to mount the secret and creating it this way avoids creating an unnecessary
# client in the keycloak realm and unnecessary secret data in the cluster.
{{- if not .Values.uds.sso.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.uds.sso.secretName }}
  namespace:  {{ .Release.Namespace }}
type: "Opaque"
stringData:
  hello-world.sso.config.key: |
    example.saml.enabled: {{ .Values.uds.sso.enabled }}
{{- end }}
