apiVersion: uds.dev/v1alpha1
kind: Package
metadata:
  name: hello-world
spec:
{{- if .Values.uds.sso.enabled }}
  sso:
    - name: Hello World Login
      clientId: uds-package-hello-world
      redirectUris:
        - "https://hello-world.{{ .Values.uds.domain }}/oauth2/callback"
      secretName: {{ .Values.uds.sso.secretName }}
      protocol: openid-connect #saml also available see https://uds.defenseunicorns.com/reference/configuration/custom-resources/packages-v1alpha1-cr/
      enableAuthserviceSelector:
        app.kubernetes.io/name: {{ .Values.uds.sso.selector }}
{{- end }}
  # Customize network policies and expose services via istio
  network:
    expose:
      - service: hello-world
        podLabels:
          app: hello-world
        gateway: tenant
        host: hello-world
        port: 8080
    allow:
      - direction: Ingress
        remoteGenerated: Anywhere

      - direction: Egress
        remoteGenerated: Anywhere

    # Custom rules for unanticipated scenarios
    {{- with .Values.additionalNetworkAllow }}
    {{ toYaml . | nindent 6 }}
    {{- end }}
