## uds-hello-world-config chart values

## hello-world chart values
image:
  repository: custom-nginx
  pullPolicy: Always
  tag: "latest"

serviceAccount:
  create: false
  automount: false

podSecurityContext: {}

securityContext:
  capabilities:
    drop:
      - ALL

service:
  port: 8080

livenessProbe:
  httpGet:
    path: /
    port: 8080

readinessProbe:
  httpGet:
    path: /
    port: 8080

uds:
  domain: "###ZARF_VAR_DOMAIN###"
  sso:
    enabled: "###ZARF_VAR_ENABLE_SSO###"
